Promise. Fetch
YARLink/Hillel-Front-End-Pro pull request #17
Opened 2022-06-12 18:52 UTC by YARLink

2022-06-13 15:59 UTC, dkhovrich requested changes

2022-06-13 15:59 UTC, dkhovrich commented on HW 16/script.js
> +    setTimeout(() => {
Не понимаю зачем тут setTimeout. Если Вы хотите сделать искусственную задержку в 1 мс, то сделайте это на промисах. Смешивать так, как у Вас, не очень правильно.

```
return wait(1000)
.then(() => load(url))
.then(data => ...)
.catch(error => ...)
```

2022-06-13 16:00 UTC, dkhovrich requested changes

2022-06-16 19:07 UTC, dkhovrich approved these changes

2022-06-16 19:07 UTC, dkhovrich commented on HW 16/script.js
> +    .catch((error) => reject(error))
Тут похоже остался вызов `reject(error)`. Надо бы убрать, больше нет такой функции.

2022-06-16 19:07 UTC, dkhovrich commented on HW 16/script.js
> +      setButtonInitialState();
Этому коду здесь не место. Функция загрузки не должна ничего знать о состоянии кнопок. Его стоит перенести сюда:
```
  load()
   .then(data => {
     renderList(data);
     if(data.info.next === null) {
       loadButton.disabled = true;
     }
   })
.finally(() => setButtonInitialState())
```

2022-06-16 19:34 UTC, YARLink commented on HW 16/script.js
> +      setButtonInitialState();
Точно, спасибо. Я еще чуял что-то неладное, но все ровно сделал

2022-06-16 19:35 UTC, YARLink commented on HW 16/script.js
> +    .catch((error) => reject(error))
Учту, спасибо

2022-06-17 07:49 UTC, merged