Homework for lesson 6. Objects.
YARLink/Hillel-Front-End-Pro pull request #3
Opened 2022-02-13 17:24 UTC by YARLink

2022-02-14 19:26 UTC, dkhovrich requested changes

2022-02-14 19:26 UTC, dkhovrich commented on Lesson 6/script.js
> +    if (typeof a, b === "object" && a, b !== null && calcObjKeys(a) === calcObjKeys(b)) {
Очень сложное условие. Я и не уверен, что оно рабочее. В условии не должно быть запятых. Попробуйте разделить на несколько условий или как-то переписать его.

2022-02-14 19:26 UTC, dkhovrich commented on Lesson 6/script.js
> +            const bothObj = typeof(a[key], b[key]) === "object";
typeof можно использовать как функцию, но очень неправильно передавать туда два аргумента. Результат очень неочевидный. Если я правильно помню, возвращается typeof от последнего аргумента.

Вообще у вас тут много лишних проверок в этой функции. Но направление правильное. 
Давайте предположим, что мы всегда передаем в эту функцию объекты. И просто их сравним.

2022-02-14 19:26 UTC, dkhovrich commented on Lesson 6/script.js
> +    for (let key in obj) {
Зачем тут цикл? Вы уже все посчитали, достаточно просто сделать `return obj;`

2022-02-15 16:43 UTC, dkhovrich approved these changes

2022-02-15 16:43 UTC, dkhovrich commented on Lesson 6/script.js
> +    if (calcObjKeys(a) === calcObjKeys(b)) {
У вас вложенное условие, что усложняет чтение. Лучше так:
```
if (calcObjKeys(a) !== calcObjKeys(b)) {
return false;
}
```
А затем уже цикл.

2022-02-15 16:43 UTC, dkhovrich commented on Lesson 6/script.js
> +        for (let key in b) {
Сделали правильно, но тут можно было еще проще:
```
for (let key in b) {
if (a[key] !== b[key] {
return false;
}                    
}
```

2022-02-15 17:27 UTC, YARLink commented on Lesson 6/script.js
> +    if (calcObjKeys(a) === calcObjKeys(b)) {
Спасибо, учту. Действительно проще

2022-02-16 08:28 UTC, merged